package com.example.odev1;

public class Odev1 {
    public static void main(String[] args) {
        String sehir = "İstanbul";
        String ulke = "Türkiye";
        int telefonNumarası = 00000000000;
        int postaKodu = 34203;
        String email = "umit@github.com";
        String meslek = "Developer";
        int stokMiktari = 5;
        String musteriAdi = "Kasım";
        double bakiye = 17.64;
        String dogumGunu = "29/10/1923";
        int maas = 11550;
        String medeniDurum = "Bekar";
        String urunYorum = "Beğendim.";
        String odemeTarihi = "20.11.2022";
        double odeme = 18.99;
        int siparisAdeti = 192;
        String arabaModeli = "Volvo XC90";
        String kitapAdi = "Dune";
        String yayinlanmaTarihi = "23/04/2021";
        int indirimMiktari = 70;
        int odaSayisi = 2;
        String enlem = "36-42 Derece Kuzey";
        String boylam = "26-45 Derece Doğu";
        String urunAdi = "Bilgisayar";
        float yemekFiyati = 173.5f;
        String marka = "Techcareer";
        String muzikAdi = "Şarkı";
        String videoSuresi = "14:48";
        double urunPuani = 4.2;
        String resimAdi = "Mona Lisa";
        String dosyaFormati = "mp4";
        String renk = "Mavi";
        String renkKodu = "#013560";
        String telefonModeli = "iPhone 14 Pro Max";
        float ekranBoyutu = 21.7f;
        double agirlik = 83.2;
        String ulusalGun = "23/04/2023";
        String tatilGun = "28/07/2023";
        String rezervasyonTarihi = "28/07/2023";
        String sokakAdi = "Gülhane Sokak";
        String otobusHatti = "98D";
        String kalanDakika = "00:01:20";
        String takipKodu = "F5S62G4S8D2G4";
        String kuponSuresi = "23:59 17/11/2022";
        String kuponKodu = "Techcareer30";
        String faturaAdresi = "abc Sokak def Apartmanı NO:1";

        System.out.println("Şehir: " + sehir);
        System.out.println("Ülke: " + ulke);
        System.out.println("Telefon: " + telefonNumarası);
        System.out.println("Posta Kodu: " + postaKodu);
        System.out.println("Email : " + email);
        System.out.println("Meslek: " + meslek);
        System.out.println("Stok Miktarı: " + stokMiktari);
        System.out.println("Müşteri Adı: " + musteriAdi);
        System.out.println("Bakiye: " + bakiye);
        System.out.println("Doğum Günü: " + dogumGunu);
        System.out.println("Maaş: " + maas);
        System.out.println("Medeni Durum: " + medeniDurum);
        System.out.println("Ürün yorumu: " + urunYorum);
        System.out.println("Ödeme Tarihi: " + odemeTarihi);
        System.out.println("Ödeme" + odeme);
        System.out.println("Sipariş Adeti: " + siparisAdeti);
        System.out.println("Araba Modeli: " + arabaModeli);
        System.out.println("Kitap Adı:" + kitapAdi);
        System.out.println("Yayınlanma Tarihi: " + yayinlanmaTarihi);
        System.out.println("İndirim Miktarı: %" + indirimMiktari);
        System.out.println("Oda Sayısı: " + odaSayisi);
        System.out.println("Enlem: " + enlem);
        System.out.println("Boylam: " + boylam);
        System.out.println("Ürün Adı: " + urunAdi);
        System.out.println("Yemek Fiyatı: " + yemekFiyati);
        System.out.println("Marka: " + marka);
        System.out.println("Müzik Adı: " + muzikAdi);
        System.out.println("Video Süresi: " + videoSuresi);
        System.out.println("Ürün Puanı: " + urunPuani);
        System.out.println("Resim Adı: " + resimAdi);
        System.out.println("Dosya Formatı: " + dosyaFormati);
        System.out.println("Renk: " + renk);
        System.out.println("Renk Kodu: " + renkKodu);
        System.out.println("Telefon Modeli: " + telefonModeli);
        System.out.println("Ekran Boyutu: " + ekranBoyutu);
        System.out.println("Ağırlık: " + agirlik);
        System.out.println("Ulusal Gün: " + ulusalGun);
        System.out.println("Tatil Günü: " + tatilGun);
        System.out.println("Rezervasyon Tarihi: " + rezervasyonTarihi);
        System.out.println("Sokak Adı: " + sokakAdi);
        System.out.println("Otobüs Hattı: " + otobusHatti);
        System.out.println("Kalan Dakika: " + kalanDakika);
        System.out.println("Takip Kodu: " + takipKodu);
        System.out.println("Kupon Süresi: " + kuponSuresi);
        System.out.println("Kupon Kodu: " + kuponKodu);
        System.out.println("Fatura Adresi: " + faturaAdresi);
    }
}
